FROM python:3.8.9-slim-buster

WORKDIR /app

RUN pip install --upgrade pip

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./stt /app/stt

COPY .env .env

COPY tmp/*.zip tmp/

RUN python stt/local/setup.py en

RUN rm tmp/*.zip

EXPOSE 2781

CMD [ "python", "./stt/server.py", "local-en" ]