version: "3.9"

services:
  stt-en_us:
    extends:
      file: stt/docker-compose-stt-local.yml
      service: stt-en_us

  stt-fr_fr:
    extends:
      file: stt/docker-compose-stt-local.yml
      service: stt-fr_fr

  stt-third-party:
    container_name: stt-third-party
    build:
      context: .
      dockerfile: stt/Dockerfile.stt-third-party
    restart: always
    ports:
      - "${STT_THIRD_PARTY_SERVER_PORT}:2700"
