version: "3.9"

services:
  stt-en_us:
    extends:
      file: kaldi-docker/docker-compose.yml
      service: stt-en_us

  stt-fr_fr:
    extends:
      file: kaldi-docker/docker-compose.yml
      service: stt-fr_fr

  stt-third-party:
    extends:
      file: docker-compose-stt.yml
      service: stt-third-party
